+another controllers
Vosker/hibernate pull request #9
Opened 2020-10-27 14:33 UTC by Vosker

OrderController
UserController
ShoppingCartController

2020-10-27 15:11 UTC, voloshynamaryna11 reviewed
good job

2020-10-27 19:47 UTC, KseniiaMakarova requested changes

2020-10-27 19:47 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controllers/OrderController.java
> +    @Autowired
sometimes you use annotation with the constructor, sometimes not
let's be consistent

2020-10-27 19:47 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controllers/mappers/CinemaHallMapper.java
> +package com.dev.cinema.controllers.mappers;
move all mappers to `service/mappers` folder

2020-10-27 19:47 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controllers/mappers/ShoppingCartMapper.java
> +    public ShoppingCartResponseDto fromEntityToDto(ShoppingCart cart) {
```suggestion
    public ShoppingCartResponseDto mapToDto(ShoppingCart cart) {
```
use uniform method names

2020-10-27 19:47 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controllers/mappers/TicketMapper.java
> +    public TicketResponseDto fromEntityToDto(Ticket ticket) {
same here

2020-10-28 08:22 UTC, KseniiaMakarova approved these changes
and fix order of imports

2020-10-28 08:22 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/service/mappers/MovieSessionMapper.java
> +    public MovieSession mapToMovie(MovieSessionRequestDto movieSessionRequestDto) {
mapToMovieSession*

2020-11-02 06:30 UTC, merged